import type { Metadata } from "next";
import { CheckCircle2, CircleX, DatabaseZap, FlaskConical } from "lucide-react";
import { staticSnapshot as snapshot } from "@/lib/static-snapshot";

export const metadata: Metadata = { title: "Methodology · NYC311 Pulse", description: "Data contracts, metric definitions, anomaly validation, privacy, and limitations for NYC311 Pulse." };
export default function MethodologyPage() {
  const locked = snapshot.evaluation.locked_test;
  const validated = snapshot.meta.model_status === "validated";
  return <main className="method-page"><header className="page-intro"><p className="eyebrow">OPEN METHODS / VERSION {snapshot.meta.method_version}</p><h1>The signal is only as useful as its boundary.</h1><p>Every transformation, threshold, evaluation result, and known limitation is exposed so the alert queue cannot outrun its evidence.</p></header>
    <section className="method-summary"><article><DatabaseZap /><span>Source</span><strong>NYC Open Data</strong><p>436,266 reconciled aggregates · fixed 24-month window</p></article><article><FlaskConical /><span>Locked evaluation</span><strong>{locked.events.toLocaleString()} injected episodes</strong><p>Independent seed · two clean generators · clustered intervals</p></article><article>{validated ? <CheckCircle2 /> : <CircleX />}<span>Release readiness</span><strong>{validated ? "Validated" : "Human review pending"}</strong><p>Synthetic and real-history gates must both pass</p></article></section>
    <section className="method-block"><div><p className="eyebrow">01 / DATA LINEAGE</p><h2>From public requests to privacy-minimized marts.</h2></div><ol className="pipeline"><li><b>Extract</b><span>Socrata pages with retries, checkpoints, and a restricted field list.</span></li><li><b>Validate</b><span>Typed contracts quarantine duplicate IDs and impossible timestamps.</span></li><li><b>Model</b><span>DuckDB and dbt build facts, dimensions, daily metrics, and closure cohorts.</span></li><li><b>Detect</b><span>Deterministic Python owns baselines, signals, ranking, and stable IDs.</span></li><li><b>Serve</b><span>FastAPI exposes aggregates only; the web app keeps a verified fallback.</span></li></ol></section>
    <section className="method-block split"><div><p className="eyebrow">02 / SELECTED VOLUME MODEL</p><h2>Matching weekdays define a count prediction interval.</h2><p>The selected Negative Binomial detector estimates weekday-specific expectation and conditional overdispersion from 26 weeks. Model and thresholds were selected on validation data only.</p></div><div className="formula"><span>{snapshot.evaluation.selected_model}</span><strong>observed &gt; expected + 3.5 × predictive scale</strong><small>Absolute excess ≥ 10 · seven-day episode cooldown</small></div></section>
    <section className="backtest-section"><div><p className="eyebrow">03 / LOCKED TEST REPORT</p><h2>Performance is reported, not implied.</h2></div><div className="backtest-grid"><article><span>Precision</span><strong>{locked.precision.toFixed(2)}</strong></article><article><span>Recall</span><strong>{locked.recall.toFixed(2)}</strong></article><article><span>F1</span><strong>{locked.f1.toFixed(2)}</strong><small>target ≥ 0.80</small></article><article><span>False episodes / week</span><strong>{locked.false_alerts_per_week.toFixed(1)}</strong><small>target ≤ 5</small></article></div><p>Actionable benchmark strengths are 2.75–5× one-day spikes, 1.75–2.5× level shifts, and ramps ending at 1.75–3×. Weaker changes may appear as research candidates but are not covered by the validated-detection claim.</p></section>
    <section className="method-block limitations"><div><p className="eyebrow">04 / LIMITATIONS</p><h2>What this product cannot tell you.</h2></div><ul><li>Request counts are not population-adjusted measures of resident need.</li><li>Resolution speed is not a direct measure of agency quality; case mix differs.</li><li>Complaint categories and statuses can change over time.</li><li>Open requests are right-censored and must remain in closure analysis.</li><li>Due Date coverage is insufficient for a citywide SLA metric.</li><li>Observed anomalies require operational context before action.</li></ul></section>
    <section className="quality-section"><div><p className="eyebrow">DATA QUALITY / JULY 2026 CHECK</p><h2>Missingness stays in the product.</h2></div><div><strong>{snapshot.quality.rows_checked.toLocaleString()}</strong><span>rows checked</span><strong>{snapshot.quality.closed_date_coverage}%</strong><span>closed-date coverage</span><strong>{snapshot.quality.quarantined_rows}</strong><span>quarantined rows</span></div></section>
  </main>;
}
